export enum BuyFloorStatus {
  CREATED = 'CREATED',
  ACQUIRED = 'ACQUIRED',
  ENDED = 'ENDED',
  TARGET_NOT_ACHIEVED = 'TARGET_NOT_ACHIEVED',
  TARGET_ACHIEVED = 'TARGET_ACHIEVED',
  NO_ITEM_AVAILABLE = 'NO_ITEM_AVAILABLE'
}
